"""
Friendly names and reference figures for Palworld 1.0.

Save files store internal asset IDs — `Sheepball`, `AIcore`, `Accessory_AirDash1`
— so every list in the dashboard used to show developer shorthand. This module
resolves those to the names players actually see, and supplies the exact
progression denominators that used to be guessed from web sources.

Data comes from `backend/data/gamedata.json.gz`, generated by
`scripts/build-gamedata.py` from the PalworldSaveTools reference archive (MIT).
It is bundled, never fetched: the container has to work offline on a LAN.

LOOKUPS ARE CASE-INSENSITIVE, deliberately. The upstream data is inconsistently
capitalised — a save records `Sheepball`, `OctopusGirl` and `SwordCutlassfish`
while the reference data spells them `SheepBall`, `OctopusGIrl` and
`SwordCutlassFish`. Exact matching silently loses eight real Pals.
"""

from __future__ import annotations

import gzip
import json
import logging
import os
import re
from typing import Any, Optional

logger = logging.getLogger(__name__)

DATA_PATH = os.environ.get(
    "GAMEDATA_PATH",
    os.path.join(os.path.dirname(os.path.abspath(__file__)), "data", "gamedata.json.gz"),
)

# Prefixes the game puts on a character ID for special variants. The underlying
# species is the same, so strip them before looking a Pal up.
_SPECIES_PREFIXES = ("BOSS_", "PREDATOR_", "SUMMON_", "RAID_")

EFFIGY_PATH = os.environ.get(
    "EFFIGY_DATA_PATH",
    os.path.join(os.path.dirname(os.path.abspath(__file__)), "data", "effigies.json.gz"),
)

BOSS_SPAWNER_PATH = os.environ.get(
    "BOSS_SPAWNER_DATA_PATH",
    os.path.join(
        os.path.dirname(os.path.abspath(__file__)), "data", "boss_spawners.json.gz"
    ),
)

GAME_SETTINGS_PATH = os.environ.get(
    "GAME_SETTINGS_DATA_PATH",
    os.path.join(
        os.path.dirname(os.path.abspath(__file__)), "data", "game_settings.json.gz"
    ),
)

WORK_ASSIGN_PATH = os.environ.get(
    "WORK_ASSIGN_DATA_PATH",
    os.path.join(
        os.path.dirname(os.path.abspath(__file__)), "data", "work_assign.json.gz"
    ),
)

BASECAMP_PATH = os.environ.get(
    "BASECAMP_DATA_PATH",
    os.path.join(
        os.path.dirname(os.path.abspath(__file__)), "data", "basecamp.json.gz"
    ),
)

ECONOMY_PATH = os.environ.get(
    "ECONOMY_DATA_PATH",
    os.path.join(
        os.path.dirname(os.path.abspath(__file__)), "data", "economy.json.gz"
    ),
)

PASSIVE_EFFECT_PATH = os.environ.get(
    "PASSIVE_EFFECT_DATA_PATH",
    os.path.join(
        os.path.dirname(os.path.abspath(__file__)), "data", "passive_effects.json.gz"
    ),
)

_data: Optional[dict[str, Any]] = None
_effigies: Optional[list[dict[str, Any]]] = None
_passive_effects: Optional[dict[str, Any]] = None
_game_settings: Optional[dict[str, Any]] = None
_boss_spawners: Optional[list[dict[str, Any]]] = None
_work_assign: Optional[dict[str, Any]] = None
_basecamp: Optional[dict[str, Any]] = None
_economy: Optional[dict[str, Any]] = None
_indexes: dict[str, dict[str, Any]] = {}


class GameDataUnavailable(Exception):
    """Raised when the bundled reference data is missing or unreadable."""


# ─── Loading ─────────────────────────────────────────────────────


def load() -> dict[str, Any]:
    """Load and cache the bundle. Cheap after the first call (~215 KB gzipped)."""
    global _data
    if _data is not None:
        return _data

    if not os.path.exists(DATA_PATH):
        raise GameDataUnavailable(
            f"Game data not found at {DATA_PATH}. "
            "Run: python3 scripts/build-gamedata.py"
        )

    try:
        with gzip.open(DATA_PATH, "rt", encoding="utf-8") as f:
            _data = json.load(f)
    except (OSError, json.JSONDecodeError) as e:
        raise GameDataUnavailable(f"Could not read {DATA_PATH}: {e}") from e

    logger.info(
        "Loaded game data: %d items, %d pals, %d technologies",
        len(_data.get("items", {})),
        len(_data.get("pals", {})),
        len(_data.get("technology", {})),
    )
    return _data


def available() -> bool:
    """Whether reference data is usable. Never raises — for health checks."""
    try:
        load()
        return True
    except GameDataUnavailable:
        return False


def _index(section: str) -> dict[str, Any]:
    """Case-insensitive index for one section, built once."""
    if section not in _indexes:
        entries = load().get(section, {})
        _indexes[section] = {key.lower(): value for key, value in entries.items()}
    return _indexes[section]


def _lookup(section: str, key: str) -> Optional[dict]:
    if not key:
        return None
    return _index(section).get(str(key).lower())


def _reset_cache() -> None:
    """
    Test hook — drops **every** module-level cache.

    It used to drop only `_data` and `_effigies`, so a test pointing
    `BOSS_SPAWNER_DATA_PATH` or `PASSIVE_EFFECT_DATA_PATH` at a fixture got
    whatever the previous test had loaded. Each bundle added since arrived with
    its own global and none were added here, which is the failure mode a partial
    reset always has: it works until it silently does not.
    """
    global _data, _effigies, _passive_effects, _game_settings
    global _boss_spawners, _work_assign, _basecamp, _economy
    _data = None
    _effigies = None
    _passive_effects = None
    _game_settings = None
    _boss_spawners = None
    _work_assign = None
    _basecamp = None
    _economy = None
    _indexes.clear()


def reload() -> dict[str, Any]:
    """
    Drop the cached bundles and read them again from disk.

    The counterpart to `worldobjects.reload()`, for the same reason: replacing a
    regenerated `gamedata.json.gz` or `effigies.json.gz` on disk should not need
    a container restart to take effect. Reports what loaded rather than only
    that it did.
    """
    _reset_cache()
    data = load()
    return {
        "gamedata": {
            "path": DATA_PATH,
            "loaded": bool(data),
            "items": len(data.get("items") or {}),
            "pals": len(data.get("pals") or {}),
            "technologies": len(data.get("technologies") or {}),
        },
        "effigies": {
            "path": EFFIGY_PATH,
            "count": len(effigies()),
        },
    }


# ─── Fallback naming ─────────────────────────────────────────────


def humanize(asset_id: str) -> str:
    """
    Best-effort display name for an ID with no reference entry.

    `PalEgg_Dragon` -> `Pal Egg Dragon`. Better than showing raw shorthand, and
    it makes a missing entry obvious rather than silently wrong.

    Only splits lowercase->uppercase boundaries. Adding an uppercase->uppercase
    rule would turn `NotAReal` into `Not A Real` but also `AIcore` into
    `A Icore`, and the two are structurally identical — no rule distinguishes
    them. Since anything with a reference entry never reaches this function, the
    simpler behaviour is the safer one.
    """
    if not asset_id:
        return ""
    spaced = re.sub(r"[_\-]+", " ", str(asset_id))
    spaced = re.sub(r"(?<=[a-z0-9])(?=[A-Z])", " ", spaced)
    return " ".join(spaced.split())


# ─── Items ───────────────────────────────────────────────────────


def item(item_id: str) -> Optional[dict]:
    return _lookup("items", item_id)


def item_name(item_id: str) -> str:
    entry = item(item_id)
    return entry["name"] if entry else humanize(item_id)


def describe_item(item_id: str) -> dict[str, Any]:
    """Everything a list row or tooltip needs, with safe fallbacks."""
    entry = item(item_id) or {}
    return {
        "id": item_id,
        "name": entry.get("name") or humanize(item_id),
        "icon": entry.get("icon", ""),
        "rarity": entry.get("rarity", 0),
        "typeA": entry.get("typeA", ""),
        "typeB": entry.get("typeB", ""),
        "maxStack": entry.get("maxStack", 0),
        "weight": entry.get("weight", 0),
        "description": entry.get("description", ""),
        "known": bool(entry),
    }


def all_items() -> list[dict[str, Any]]:
    """
    The whole item catalogue — every id the game has, not the ones a world holds.

    The distinction is the bug this exists for. The slot editor's autocomplete
    was built from `/api/items`, which reports **what is in the parsed world**,
    so typing any legitimate item nobody on the server happened to own showed
    "not in this world" with no icon. The backend accepted it on preview, having
    always validated against this full catalogue — so the editor was telling
    people their input was wrong and then writing it correctly.

    `id` and `name` both travel because the API speaks ids (`AIcore`) and people
    speak names ("AI Core"), and a catalogue that carries only one of them forces
    every caller to build the other index itself.
    """
    entries = (load().get("items") or {})
    return [
        {
            "id": item_id,
            "name": entry.get("name") or humanize(item_id),
            "icon": entry.get("icon", ""),
            "rarity": entry.get("rarity", 0),
            "typeA": entry.get("typeA", ""),
            "typeB": entry.get("typeB", ""),
            "maxStack": entry.get("maxStack", 0),
            "weight": entry.get("weight", 0),
            # Present only on equipment. The editor uses it to warn *before* a
            # preview that a slot cannot be overwritten without orphaning a
            # DynamicItemSaveData record.
            "hasDurability": bool((entry.get("dynamic") or {}).get("type")),
        }
        for item_id, entry in sorted(entries.items())
    ]


def max_stack(item_id: str) -> int:
    """
    The game's real stack ceiling, or 0 if unknown.

    saveedit currently infers a ceiling from the largest stack present in the
    save. This is the authoritative figure, but swapping it in changes what a
    sort writes, so that is a deliberate change and not a drive-by one.
    """
    entry = item(item_id)
    return int(entry.get("maxStack") or 0) if entry else 0


# ─── Pals ────────────────────────────────────────────────────────


def normalise_species(species_id: str) -> tuple[str, list[str]]:
    """Strip BOSS_/PREDATOR_/etc, returning (species, prefixes_found)."""
    remaining = str(species_id or "")
    found: list[str] = []
    changed = True
    while changed:
        changed = False
        for prefix in _SPECIES_PREFIXES:
            if remaining.upper().startswith(prefix):
                found.append(prefix.rstrip("_"))
                remaining = remaining[len(prefix):]
                changed = True
    return remaining, found


def pal(species_id: str) -> Optional[dict]:
    species, _ = normalise_species(species_id)
    return _lookup("pals", species)


def pal_exact(species_id: str) -> Optional[dict]:
    """
    A species' own entry, **without** stripping `BOSS_` and friends.

    `pal()` normalises, which is right for naming — an alpha Lamball is still
    called Lamball — and wrong for anything that reads the numbers, because the
    prefixed forms carry their own, higher, stat scaling. `BOSS_Alpaca` has hp
    108 where `Alpaca` has 90, and that difference *is* the alpha bonus. Look up
    the base species and the bonus silently disappears; apply a separate boss
    multiplier on top of the base and it gets counted twice.

    Falls back to the normalised lookup, so a form present in a save but absent
    from the tables still resolves to something rather than to nothing.
    """
    return _lookup("pals", species_id) or pal(species_id)


def pal_exp_table() -> dict[str, Any]:
    """
    The game's own level -> EXP table. `{}` if the bundle is unavailable.

    Two columns per level, and picking the wrong one is easy: `PalNextEXP` is
    the Pal curve and `NextEXP` beside it is the *player* curve. They differ
    from level 2 onwards (25 vs 50).
    """
    return load().get("palExpTable") or {}


def pal_name(species_id: str) -> str:
    entry = pal(species_id)
    if entry:
        return entry["name"]
    species, _ = normalise_species(species_id)
    return humanize(species)


def describe_pal(species_id: str) -> dict[str, Any]:
    species, prefixes = normalise_species(species_id)
    entry = pal(species_id) or {}
    return {
        "id": species_id,
        "species": species,
        "name": entry.get("name") or humanize(species),
        "icon": entry.get("icon", ""),
        "elements": entry.get("elements", []),
        "rarity": entry.get("rarity", 0),
        "paldeckNumber": entry.get("zukanIndex", 0),
        "workSuitabilities": entry.get("workSuitabilities", {}),
        "variants": prefixes,
        "known": bool(entry),
    }


def npc_name(npc_id: str) -> str:
    entry = _lookup("npcs", npc_id)
    return entry["name"] if entry else humanize(npc_id)


def character(character_id: str) -> Optional[dict]:
    """
    The record for anything in CharacterSaveParameterMap, Pal or human.

    `pal()` alone answers "is this a known Pal", which is not the same question
    as "is this a known character". On the reference world 100 of the 1,905
    entries are NPCs — guards, merchants, villagers — so treating a Pal-table
    miss as "unrecognised" flags a clean world as full of modded content.
    """
    species, _ = normalise_species(character_id)
    return _lookup("pals", species) or _lookup("npcs", species)


def character_name(character_id: str) -> str:
    """
    Name for anything in CharacterSaveParameterMap.

    That map holds humans as well as Pals — merchants, guards, tower bosses — so
    a Pal-only lookup leaves a good fraction of a real world showing internal IDs
    like `Believer_CrossBow` instead of `Free Pal Alliance Believer`.
    """
    species, _ = normalise_species(character_id)
    entry = _lookup("pals", species) or _lookup("npcs", species)
    return entry["name"] if entry else humanize(species)


# ─── Skills ──────────────────────────────────────────────────────


def passive_name(passive_id: str) -> str:
    entry = _lookup("passives", passive_id)
    return entry["name"] if entry else humanize(passive_id)


def describe_passive(passive_id: str) -> dict[str, Any]:
    entry = _lookup("passives", passive_id) or {}
    return {
        "id": passive_id,
        "name": entry.get("name") or humanize(passive_id),
        "rank": entry.get("rank", 0),
        "icon": entry.get("icon", ""),
        "description": entry.get("description", ""),
        "known": bool(entry),
    }


def skill_name(skill_id: str) -> str:
    """Active skill. Save IDs arrive as `EPalWazaID::PowerBall`."""
    cleaned = str(skill_id or "").split("::")[-1]
    entry = _lookup("activeSkills", cleaned)
    return entry["name"] if entry else humanize(cleaned)


# ─── Technology & structures ─────────────────────────────────────


def technology(tech_id: str) -> Optional[dict]:
    return _lookup("technology", tech_id)


def technology_name(tech_id: str) -> str:
    entry = technology(tech_id)
    return entry["name"] if entry else humanize(tech_id)


def structure_name(structure_id: str) -> str:
    entry = _lookup("structures", structure_id)
    return entry["name"] if entry else humanize(structure_id)


# ─── World data ──────────────────────────────────────────────────


def effigies() -> list[dict[str, Any]]:
    """
    All 396 effigies, each with world coordinates **and its instance GUID**.

    The GUID is the useful part. A save's `RelicObtainForInstanceFlag` keys on
    exactly these values, so a player's collected set joins directly against
    this list — which is what makes "show me the ones I have not found" possible
    rather than just "here are all of them".

    Extracted from the game pak by `scripts/extract-effigies.py`; every position
    is verified to land in a streaming cell the game ships content for, and
    every effigy the reference world's players had collected (37 of 37) appears
    here. Returns an empty list rather than raising if the bundle is absent, so
    a missing file degrades the map instead of breaking it.
    """
    global _effigies
    if _effigies is not None:
        return _effigies

    try:
        with gzip.open(EFFIGY_PATH, "rt", encoding="utf-8") as f:
            _effigies = json.load(f).get("effigies") or []
    except (OSError, json.JSONDecodeError) as e:
        logger.warning("Effigy data unavailable (%s); the map will omit them", e)
        _effigies = []

    for effigy in _effigies:
        effigy["kindName"] = effigy_kind_name(str(effigy.get("kind") or ""))
    return _effigies


def boss_spawners() -> list[dict[str, Any]]:
    """
    The 90 placed field bosses: species, **level** and world position.

    From `DT_BossSpawnerLoactionData` via `scripts/extract-boss-spawners.py`.
    Levels were documented as unavailable across this project for months — they
    were behind a reader refusal, not absent.

    **Positions are verified, not assumed.** All 90 land on an occupied World
    Partition cell at 25,600 units, with controls at 12,800 (22) and 51,200 (83)
    both worse. The extractor refuses to write if that stops being true.

    Empty list rather than raising when the bundle is absent, like `effigies()`:
    a missing file should cost the layer, not the map.
    """
    global _boss_spawners
    if _boss_spawners is None:
        try:
            with gzip.open(BOSS_SPAWNER_PATH, "rt", encoding="utf-8") as f:
                _boss_spawners = json.load(f).get("bosses") or []
        except (OSError, json.JSONDecodeError) as e:
            logger.warning(
                "Boss spawner data unavailable (%s); the layer will be empty", e
            )
            _boss_spawners = []
    return _boss_spawners


def describe_boss(entry: dict[str, Any]) -> dict[str, Any]:
    """One boss row with its display name and artwork joined on."""
    species = str(entry.get("speciesId") or "")
    info = pal(species) or {}
    return {
        **entry,
        # `pal()` strips the BOSS_ prefix, which is right for naming: an alpha
        # Lamball is still called Lamball. Stats would need `pal_exact`.
        "name": info.get("name") or humanize(species),
        "icon": info.get("icon", ""),
        "elements": info.get("elements") or [],
        "paldeckNumber": info.get("paldeckNumber"),
    }


def work_assign(structure_id: str) -> Optional[dict[str, Any]]:
    """
    Which work a structure needs, from `DT_MapObjectAssignData`.

    Returns None for anything not in the table, and **that is a meaningful
    answer rather than a gap**: the structures absent from it are exactly the
    ones no Pal is ever assigned to. On the reference world 44 of 63 base-placed
    kinds resolve and the 19 that do not are chests, beds, the palbox, the spa,
    walls and the food boxes. `test_work_assign.py` pins that.

    **Case-insensitive**, like every other lookup here: the save spells it
    `Workbench` and the table says `WorkBench`, so an exact match loses a real
    structure without saying so.

    A structure can need more than one kind of work — a farm plot needs Seeding,
    Watering and Collection — so `slots` is a list. Reading only the first
    answers a third of the question and looks complete.
    """
    global _work_assign
    if _work_assign is None:
        try:
            with gzip.open(WORK_ASSIGN_PATH, "rt", encoding="utf-8") as f:
                objects = json.load(f).get("objects") or {}
            # Keyed lowercase on load rather than lowercasing per lookup: this
            # is read once per structure in a per-base walk.
            _work_assign = {str(k).lower(): v for k, v in objects.items()}
        except (OSError, json.JSONDecodeError) as e:
            logger.warning(
                "Work assignment data unavailable (%s); per-structure work "
                "requirements will be unknown", e
            )
            _work_assign = {}
    return _work_assign.get(str(structure_id or "").lower())


def work_assign_available() -> bool:
    """
    Whether the bundle loaded at all.

    Distinct from a structure simply not being in it, which is normal. A caller
    reporting "this base needs no work" must be able to tell the two apart —
    that is the `.catch(() => [])` lesson: an empty answer and a failed load
    must not share a representation.
    """
    work_assign("")
    return bool(_work_assign)


def basecamp() -> dict[str, Any]:
    """
    Base camp levels, illness penalties and worker sanity thresholds.

    Three small tables bundled together because they answer one question — what
    is happening at a base and whether it is coping.

    Empty dict rather than raising when the bundle is absent, like every other
    accessor here: a missing file should cost the panel, not the page.
    """
    global _basecamp
    if _basecamp is None:
        try:
            with gzip.open(BASECAMP_PATH, "rt", encoding="utf-8") as f:
                _basecamp = json.load(f)
        except (OSError, json.JSONDecodeError) as e:
            logger.warning(
                "Base camp data unavailable (%s); worker caps and illness "
                "detail will be missing", e
            )
            _basecamp = {}
    return _basecamp


def base_worker_cap(level: int) -> Optional[int]:
    """
    How many Pals a base of this level may hold **in an unmodified game**.

    THIS IS NOT THE CAP ON ANY PARTICULAR SERVER, IT IS NOT A MAXIMUM, AND IT IS
    NOT A FALLBACK. Two things override it:

    1. **`BaseCampWorkerMaxNum` in `PalWorldSettings.ini`** — a server setting.
       The shipped default is **15** against this table's 30, and a real server
       in use runs 25 workers and 5 bases per guild where the table says 30 and
       4. It is over in one direction and under in the other, which is what
       proves the table bounds nothing. `server_worker_cap()` reads the real
       value and returns None rather than substituting this one.

    2. **The base's level**, which gates how much of the cap is unlocked — a
       level-1 base holds one Pal whatever the server allows.

    And the catch that makes (2) unusable today: **base level is not in the
    save.** `BaseCampSaveData.RawData` carries id, name, state, transform,
    area_range, group and the owning palbox's instance id, and nothing else; the
    palbox's own model and concrete model carry no level either. So this function
    has no caller that can supply an argument to it yet. It is bundled because
    the table is real and the level will turn up somewhere (`unknown_bytes` on
    the palbox model is the obvious place to look next), not because anything
    uses it.

    Returns None for a level the table does not cover rather than clamping to the
    nearest — "cap unknown" and "cap is 30" are different answers.
    """
    for row in basecamp().get("levels") or []:
        if int(row.get("level") or 0) == int(level or 0):
            return int(row.get("workerMax") or 0)
    return None


# The INI keys that actually govern. The DataTable is a *default*, not a bound —
# see `server_limit`.
WORKER_CAP_SETTING = "BaseCampWorkerMaxNum"
BASES_PER_GUILD_SETTING = "BaseCampMaxNumInGuild"
BASES_TOTAL_SETTING = "BaseCampMaxNum"


def server_limit(setting: str) -> Optional[int]:
    """
    One of this server's own limits, read from its INI.

    **THE INI IS THE ONLY AUTHORITY AND THE BUNDLED TABLE BOUNDS NOTHING.** That
    is measured, not cautious: `DT_BaseCampLevelData` tops out at 4 bases per
    guild and 30 workers, and a real server in use runs **5 bases and 25
    workers** — over the table in one direction and under it in the other. So the
    table cannot be used as a ceiling, a floor, or a fallback. It describes an
    unmodified game and nothing else.

    Nor is there a hard maximum to fall back on: `BaseCampMaxNum` defaults to 128
    and is itself a setting. Every one of these numbers is the operator's.

    None when the INI cannot be read, which is the *common* case — the normal
    deployment mounts only the save path. **None means "not known", never
    "unlimited" and never "use the game's value"**: a caller must show no
    denominator rather than a wrong one, the same way `iniwatch` treats
    `unknown` as a real answer rather than as "safe".
    """
    try:
        import settings_ini

        options = settings_ini.read_ini()
    except Exception as e:  # noqa: BLE001 - an unreadable INI is normal here
        logger.debug("Cannot read %s from the INI (%s)", setting, e)
        return None

    entry = (options.get("options") or {}).get(setting)
    if isinstance(entry, dict):
        entry = entry.get("value")
    try:
        return int(entry)
    except (TypeError, ValueError):
        return None


def server_worker_cap() -> Optional[int]:
    """How many Pals a base may hold on **this** server."""
    return server_limit(WORKER_CAP_SETTING)


def server_bases_per_guild() -> Optional[int]:
    """How many bases a guild may build on **this** server."""
    return server_limit(BASES_PER_GUILD_SETTING)


def illness(sick_id: str) -> Optional[dict[str, Any]]:
    """
    What one illness costs: work speed, move speed, satiety, and the chance the
    palbox clears it per hour.

    `EffectiveItemRank` travels but is deliberately NOT resolved to a medicine
    item here. Which item clears which rank is unverified, and naming one would
    be the sort of mechanic claim `basesupply` refuses to make.
    """
    key = str(sick_id or "").lower()
    for row in basecamp().get("illnesses") or []:
        if str(row.get("id") or "").lower() == key:
            return row
    return None


def worker_sanity_thresholds() -> list[dict[str, Any]]:
    """
    The sanity levels at which a worker misbehaves, highest first.

    **These are not the same number as `main.LOW_SANITY`.** That is 50, from
    `FriendshipPoint_AutoIncrementRequireSanity` — the sanity a Pal needs to keep
    gaining *trust*. A worker starts taking short breaks at 85 and has stopped
    being useful well before 50, so a panel warning at 50 is answering a
    different question from the one it appears to answer.
    """
    return basecamp().get("workerEvents") or []


def economy() -> dict[str, Any]:
    """
    Recipes, Pal drops, loot tables, shops, food effects and production yields.

    From the server pak via `scripts/extract-economy.py`. Empty dict when the
    bundle is absent, like every accessor here.
    """
    global _economy
    if _economy is None:
        try:
            with gzip.open(ECONOMY_PATH, "rt", encoding="utf-8") as f:
                _economy = json.load(f)
        except (OSError, json.JSONDecodeError) as e:
            logger.warning(
                "Economy data unavailable (%s); recipes, drops and shop stock "
                "will be missing", e
            )
            _economy = {}
    return _economy


def recipe(item_id: str) -> Optional[dict[str, Any]]:
    """
    How one item is crafted: materials, counts and work amount.

    **Keyed by product, which collapses 1,414 rows to 1,399.** Fifteen products
    have more than one recipe row and only one survives. That is right for "how
    do I make X" and wrong for "every way to make X" — if the second question
    ever matters, the extractor needs to emit a list.

    Which *bench* crafts it is not here, and not anywhere: `WorkableAttribute`
    is present on every recipe row and is 0 on all of them.
    """
    return (economy().get("recipes") or {}).get(str(item_id or ""))


def drops_for(species_id: str) -> list[dict[str, Any]]:
    """
    What a species drops, by level band.

    **`levelFrom` is a band, not a level.** The column holds only 0, 10, 20 … 80,
    so a row covers "level 30-39". Interpolating between bands would be
    inventing numbers the game does not have.

    Case-insensitive, and `BOSS_`-prefixed variants have their own tables — an
    alpha drops differently from the ordinary form, so this does *not* strip the
    prefix the way `pal()` does.
    """
    table = economy().get("drops") or {}
    key = str(species_id or "")
    if key in table:
        return table[key]
    lowered = key.lower()
    for name, rows in table.items():
        if name.lower() == lowered:
            return rows
    return []


def dropped_by(item_id: str) -> list[dict[str, Any]]:
    """
    Which species drop this item, with rates — the reverse lookup, and the one
    a player actually asks ("where do I get Leather?").

    Scans rather than indexes: ~890 species with a handful of bands each is a
    few thousand comparisons, and building a reverse index would need
    invalidating alongside the forward one for no measurable gain.
    """
    wanted = str(item_id or "").lower()
    if not wanted:
        return []
    out = []
    for species, bands in (economy().get("drops") or {}).items():
        for band in bands:
            for entry in band.get("items") or []:
                if str(entry.get("itemId") or "").lower() == wanted:
                    out.append({
                        "speciesId": species,
                        "levelFrom": band.get("levelFrom"),
                        **entry,
                    })
    out.sort(key=lambda r: (-float(r.get("rate") or 0), r["speciesId"]))
    return out


def food_effect(item_id: str) -> Optional[dict[str, Any]]:
    """What a cooked dish does, and for how long."""
    return (economy().get("food") or {}).get(str(item_id or ""))


def game_setting(name: str, default: Any = None) -> Any:
    """
    One of Pocketpair's own tuning constants, from `BP_PalGameSetting`.

    347 of them, decoded from the Blueprint's class-default object by
    `scripts/extract-game-settings.py` — damage rates, sanity and hunger
    thresholds, capture rates, base-camp ranges. This is the answer to "surely
    that number is in the files somewhere", which it usually is.

    THE DECODE VERIFIES ITSELF: `CharacterMaxLevel` comes out 80 and
    `CharacterMaxRank` 5, two constants this project already held from sources
    that explicitly could not be checked against the install. A misaligned walk
    does not land two independently-known values in the right places.

    Case-sensitive, unlike the id lookups here — these are UPROPERTY names with
    one fixed spelling rather than ids three files disagree about.
    """
    global _game_settings
    if _game_settings is None:
        try:
            with gzip.open(GAME_SETTINGS_PATH, "rt", encoding="utf-8") as f:
                _game_settings = json.load(f)
        except (OSError, json.JSONDecodeError) as e:
            logger.warning(
                "Game settings unavailable (%s); callers fall back to their own "
                "documented defaults", e,
            )
            _game_settings = {}
    value = _game_settings.get(name)
    return default if value is None else value


def passive_effects(passive_id: str) -> Optional[dict[str, Any]]:
    """
    The *numeric* effects of one passive skill, or None if it is not bundled.

    The `passives` section of `gamedata.json.gz` carries a **sentence** —
    "Attack +5%" — which is right for showing a player and useless for computing
    anything. This is `DT_PassiveSkill_Main` out of the server pak, extracted by
    `scripts/extract-passive-effects.py`:

        {"rank": 4,
         "effects": [{"type": "ShotAttack", "value": 20.0, "target": "ToSelf"},
                     {"type": "Defense",    "value": 20.0, "target": "ToSelf"}],
         "invoke": ["InvokeAlways"], "lotteryWeight": 10, "element": ""}

    VERIFIED AGAINST THE GAME'S OWN PROSE: of the 1,897 bundled passives, 1,754
    have a numeric English description and **1,754 match**, on 5 exceptions —
    four of which are the PST archive's descriptions failing to substitute their
    own `{EffectValue1}` placeholder, so the table is right and the sentence is
    broken. The remaining one (`FullStomach_Down_1_BossDefeat`, prose "+10.0%
    slower" against a stored -1.0) is a real disagreement and is not resolved.

    Case-insensitive like every other lookup here, for the reason the module
    docstring gives.
    """
    global _passive_effects
    if _passive_effects is None:
        try:
            with gzip.open(PASSIVE_EFFECT_PATH, "rt", encoding="utf-8") as f:
                raw = json.load(f)
            _passive_effects = {str(k).lower(): v for k, v in raw.items()}
        except (OSError, json.JSONDecodeError) as e:
            # Degrade rather than raise: without this bundle a stat simply
            # carries no passive term, which is exactly what it did before the
            # bundle existed. A missing file must not take out /api/pals.
            logger.warning(
                "Passive effect data unavailable (%s); stats will omit the "
                "passive term", e,
            )
            _passive_effects = {}
    return _passive_effects.get(str(passive_id or "").lower())


def effigy_kind_name(kind: str) -> str:
    """
    A blueprint class like `BP_LevelObject_Relic_SheepBall` -> "Lamball Effigy".

    THE SUFFIX IS A SPECIES ID, WHICH IS WHY THIS IS NOT A STRING TIDY-UP.
    The map's generic `prettyClass` helper turned these into "Relic Sheep Ball"
    and "BP Relic Object" — de-underscored game-file names shown to players in
    the effigy filter list. Splitting the words is not the same as knowing what
    they mean: `SheepBall` is the internal id for **Lamball**, and only
    `gamedata.pal_name` knows that.

    Resolution is deliberately through `pal_name`, so the case-insensitivity
    applies. The upstream ids are inconsistently capitalised — the extraction
    yields `SheepBall` while the Pal table spells it `Sheepball` — and an exact
    match would silently fall through to the raw name for exactly the entries
    this exists to fix.

    Unrecognised suffixes fall back to a humanised form rather than failing, and
    the two unsuffixed classes (`BP_LevelObject_Relic`, `BP_RelicObject` — 155 of
    the 396 between them) are plain "Effigy", because they genuinely are not
    tied to a species.
    """
    if not kind:
        return "Effigy"

    for prefix in ("BP_LevelObject_Relic_", "BP_RelicObject_"):
        if kind.startswith(prefix):
            species = kind[len(prefix):]
            return f"{pal_name(species)} Effigy" if species else "Effigy"

    if kind in ("BP_LevelObject_Relic", "BP_RelicObject"):
        return "Effigy"
    return f"{humanize(kind)} Effigy"


def fast_travel_kind(name: str) -> str:
    """
    `tower`, `watchtower` or `travel` for one fast-travel point.

    **The tower bosses are already in this table and nothing said so.** All 174
    points rendered as one identical gold marker, so "where are the towers" had
    no answer on a map that was in fact showing all eight of them — the eight
    named `… Tower Entrance`. Splitting the layer by kind was the fix; extracting
    anything new from the pak was not needed and would have been the wrong tree.

    Classified from the localized name rather than from an id, because the name
    is the only field that distinguishes them — the keys are opaque hex. That
    means this is **English-dependent**, and it fails to the safe side: an
    unrecognised name is a plain travel point, which is what every point was
    before this existed.

    The distinction matters because they are different things: a Tower Entrance
    is a boss arena you clear once, a Watchtower is scenery with a statue at the
    bottom, and neither is the other.
    """
    lowered = name.lower()
    if lowered.endswith("tower entrance"):
        return "tower"
    if "watchtower" in lowered:
        return "watchtower"
    return "travel"


def fast_travel_points() -> list[dict[str, Any]]:
    """
    All 174 fast-travel points with world coordinates and localized names.

    Coordinates share the save's world space, so they feed the existing map
    transform unchanged. Covers both landmasses — 17 of these sit on the World
    Tree side.

    Measured split: **8 tower entrances, 22 watchtowers, 144 ordinary points** —
    and the eight are exactly Palworld's eight tower bosses, which is the check
    that the name rule is picking out the right thing rather than merely
    something.
    """
    return [
        {"key": key, "kind": fast_travel_kind(str(value.get("name") or "")), **value}
        for key, value in sorted(load().get("fastTravel", {}).items())
    ]


def fast_travel_name(point_id: str) -> str:
    entry = _lookup("fastTravel", point_id)
    return entry["name"] if entry else humanize(point_id)


def work_suitabilities() -> list[dict[str, Any]]:
    return load().get("workSuitability", [])


# ─── Reference totals ────────────────────────────────────────────


def totals() -> dict[str, Any]:
    """
    Exact Palworld 1.0 figures, computed from the game's own data tables.

    These replace the previously web-sourced estimates. Notably: 1,413 ordinary
    technology points across 537 technologies, and 185 ancient technology points
    across 51 boss technologies.
    """
    return dict(load().get("totals", {}))
