"""
Friendly names and reference figures for Palworld 1.0.

Save files store internal asset IDs — `Sheepball`, `AIcore`, `Accessory_AirDash1`
— so every list in the dashboard used to show developer shorthand. This module
resolves those to the names players actually see, and supplies the exact
progression denominators that used to be guessed from web sources.

Data comes from `backend/data/gamedata.json.gz`, generated by
`scripts/build-gamedata.py`. It is bundled, never fetched: the container has to
work offline on a LAN.

**THE STRINGS AND THE NUMBERS BOTH COME FROM THE GAME NOW.** Numbers are the
server pak's DataTables (verified against the previous third-party catalogue,
13,836 of 13,836 values agreeing); display names and descriptions are the client
pak's `L10N/en` overrides, read by `scripts/l10n.py` and joined by
`scripts/gametext.py`. The reference archive still supplies icon paths and the
list of which ids exist, and it still names the entries the game leaves
untranslated — `build-gamedata.py` prints that count per section rather than
letting it pass as complete coverage.

LOOKUPS ARE CASE-INSENSITIVE, deliberately. The upstream data is inconsistently
capitalised — a save records `Sheepball`, `OctopusGirl` and `SwordCutlassfish`
while the reference data spells them `SheepBall`, `OctopusGIrl` and
`SwordCutlassFish`. Exact matching silently loses eight real Pals. The game's own
data has the same problem in its rich-text tags, which ship three spellings of
`mapObjectName`.

**Names the game gives are not always the ones the archive gave**, and where they
differ the game wins:

- Accessory tiers are distinct. `Accessory_AT_2` is "Attack Pendant **+1**"; the
  archive called all three tiers "Attack Pendant", so three different items
  shared one name.
- `BOSS_`/`GYM_` forms are named for the species, without the archive's `(Boss)`
  and `(Gym)` decorations. That agrees with this module's own rule that an alpha
  Lamball is still called Lamball, and `isBoss` travels separately.
"""

from __future__ import annotations

import gzip
import json
import logging
import os
import re
from typing import Any, Optional

logger = logging.getLogger(__name__)

DATA_PATH = os.environ.get(
    "GAMEDATA_PATH",
    os.path.join(os.path.dirname(os.path.abspath(__file__)), "data", "gamedata.json.gz"),
)

# Prefixes the game puts on a character ID for special variants. The underlying
# species is the same, so strip them before looking a Pal up.
_SPECIES_PREFIXES = ("BOSS_", "PREDATOR_", "SUMMON_", "RAID_")

EFFIGY_PATH = os.environ.get(
    "EFFIGY_DATA_PATH",
    os.path.join(os.path.dirname(os.path.abspath(__file__)), "data", "effigies.json.gz"),
)

BOSS_SPAWNER_PATH = os.environ.get(
    "BOSS_SPAWNER_DATA_PATH",
    os.path.join(
        os.path.dirname(os.path.abspath(__file__)), "data", "boss_spawners.json.gz"
    ),
)

GAME_SETTINGS_PATH = os.environ.get(
    "GAME_SETTINGS_DATA_PATH",
    os.path.join(
        os.path.dirname(os.path.abspath(__file__)), "data", "game_settings.json.gz"
    ),
)

WORK_ASSIGN_PATH = os.environ.get(
    "WORK_ASSIGN_DATA_PATH",
    os.path.join(
        os.path.dirname(os.path.abspath(__file__)), "data", "work_assign.json.gz"
    ),
)

BASECAMP_PATH = os.environ.get(
    "BASECAMP_DATA_PATH",
    os.path.join(
        os.path.dirname(os.path.abspath(__file__)), "data", "basecamp.json.gz"
    ),
)

ECONOMY_PATH = os.environ.get(
    "ECONOMY_DATA_PATH",
    os.path.join(
        os.path.dirname(os.path.abspath(__file__)), "data", "economy.json.gz"
    ),
)

SPAWNS_PATH = os.environ.get(
    "SPAWNS_DATA_PATH",
    os.path.join(os.path.dirname(os.path.abspath(__file__)), "data", "spawns.json.gz"),
)

MOVES_PATH = os.environ.get(
    "MOVES_DATA_PATH",
    os.path.join(os.path.dirname(os.path.abspath(__file__)), "data", "moves.json.gz"),
)

PROGRESSION_PATH = os.environ.get(
    "PROGRESSION_DATA_PATH",
    os.path.join(
        os.path.dirname(os.path.abspath(__file__)), "data", "progression.json.gz"
    ),
)

RAIDBOSS_PATH = os.environ.get(
    "RAIDBOSS_DATA_PATH",
    os.path.join(os.path.dirname(os.path.abspath(__file__)), "data", "raidbosses.json.gz"),
)

INVADERS_PATH = os.environ.get(
    "INVADERS_DATA_PATH",
    os.path.join(os.path.dirname(os.path.abspath(__file__)), "data", "invaders.json.gz"),
)

WORLDPRESETS_PATH = os.environ.get(
    "WORLDPRESETS_DATA_PATH",
    os.path.join(os.path.dirname(os.path.abspath(__file__)), "data", "worldpresets.json.gz"),
)

NPCS_PATH = os.environ.get(
    "NPCS_DATA_PATH",
    os.path.join(os.path.dirname(os.path.abspath(__file__)), "data", "npcs.json.gz"),
)

PASSIVE_EFFECT_PATH = os.environ.get(
    "PASSIVE_EFFECT_DATA_PATH",
    os.path.join(
        os.path.dirname(os.path.abspath(__file__)), "data", "passive_effects.json.gz"
    ),
)

_data: Optional[dict[str, Any]] = None
_effigies: Optional[list[dict[str, Any]]] = None
_passive_effects: Optional[dict[str, Any]] = None
_game_settings: Optional[dict[str, Any]] = None
_boss_spawners: Optional[list[dict[str, Any]]] = None
_work_assign: Optional[dict[str, Any]] = None
_basecamp: Optional[dict[str, Any]] = None
_economy: Optional[dict[str, Any]] = None
_spawns: Optional[dict[str, Any]] = None
_moves: Optional[dict[str, Any]] = None
_progression: Optional[dict[str, Any]] = None
_raidbosses: Optional[dict[str, Any]] = None
_invaders: Optional[dict[str, Any]] = None
_worldpresets: Optional[dict[str, Any]] = None
_npcs: Optional[dict[str, Any]] = None
_guild: Optional[dict[str, Any]] = None
_indexes: dict[str, dict[str, Any]] = {}


class GameDataUnavailable(Exception):
    """Raised when the bundled reference data is missing or unreadable."""


# ─── Loading ─────────────────────────────────────────────────────


def load() -> dict[str, Any]:
    """Load and cache the bundle. Cheap after the first call (~215 KB gzipped)."""
    global _data
    if _data is not None:
        return _data

    if not os.path.exists(DATA_PATH):
        raise GameDataUnavailable(
            f"Game data not found at {DATA_PATH}. "
            "Run: python3 scripts/build-gamedata.py"
        )

    try:
        with gzip.open(DATA_PATH, "rt", encoding="utf-8") as f:
            _data = json.load(f)
    except (OSError, json.JSONDecodeError) as e:
        raise GameDataUnavailable(f"Could not read {DATA_PATH}: {e}") from e

    logger.info(
        "Loaded game data: %d items, %d pals, %d technologies",
        len(_data.get("items", {})),
        len(_data.get("pals", {})),
        len(_data.get("technology", {})),
    )
    return _data


def available() -> bool:
    """Whether reference data is usable. Never raises — for health checks."""
    try:
        load()
        return True
    except GameDataUnavailable:
        return False


def _index(section: str) -> dict[str, Any]:
    """Case-insensitive index for one section, built once."""
    if section not in _indexes:
        entries = load().get(section, {})
        _indexes[section] = {key.lower(): value for key, value in entries.items()}
    return _indexes[section]


def _lookup(section: str, key: str) -> Optional[dict]:
    if not key:
        return None
    return _index(section).get(str(key).lower())


def _reset_cache() -> None:
    """
    Test hook — drops **every** module-level cache.

    It used to drop only `_data` and `_effigies`, so a test pointing
    `BOSS_SPAWNER_DATA_PATH` or `PASSIVE_EFFECT_DATA_PATH` at a fixture got
    whatever the previous test had loaded. Each bundle added since arrived with
    its own global and none were added here, which is the failure mode a partial
    reset always has: it works until it silently does not.
    """
    global _data, _effigies, _passive_effects, _game_settings
    global _boss_spawners, _work_assign, _basecamp, _economy, _spawns, _moves
    global _npcs, _guild
    global _progression, _raidbosses, _invaders, _worldpresets
    # Derived from `_boss_spawners`, so it has to go with it — a stale index
    # would keep answering from the bundle that was just replaced.
    global _boss_level_index
    _boss_level_index = None
    _data = None
    _effigies = None
    _passive_effects = None
    _game_settings = None
    _boss_spawners = None
    _work_assign = None
    _basecamp = None
    _economy = None
    _npcs = None
    _guild = None
    _spawns = None
    _moves = None
    _progression = None
    _raidbosses = None
    _invaders = None
    _worldpresets = None
    _indexes.clear()


def reload() -> dict[str, Any]:
    """
    Drop the cached bundles and read them again from disk.

    The counterpart to `worldobjects.reload()`, for the same reason: replacing a
    regenerated `gamedata.json.gz` or `effigies.json.gz` on disk should not need
    a container restart to take effect. Reports what loaded rather than only
    that it did.
    """
    _reset_cache()
    data = load()
    return {
        "gamedata": {
            "path": DATA_PATH,
            "loaded": bool(data),
            "items": len(data.get("items") or {}),
            "pals": len(data.get("pals") or {}),
            "technologies": len(data.get("technologies") or {}),
        },
        "effigies": {
            "path": EFFIGY_PATH,
            "count": len(effigies()),
        },
    }


# ─── Fallback naming ─────────────────────────────────────────────


def humanize(asset_id: str) -> str:
    """
    Best-effort display name for an ID with no reference entry.

    `PalEgg_Dragon` -> `Pal Egg Dragon`. Better than showing raw shorthand, and
    it makes a missing entry obvious rather than silently wrong.

    Only splits lowercase->uppercase boundaries. Adding an uppercase->uppercase
    rule would turn `NotAReal` into `Not A Real` but also `AIcore` into
    `A Icore`, and the two are structurally identical — no rule distinguishes
    them. Since anything with a reference entry never reaches this function, the
    simpler behaviour is the safer one.
    """
    if not asset_id:
        return ""
    spaced = re.sub(r"[_\-]+", " ", str(asset_id))
    spaced = re.sub(r"(?<=[a-z0-9])(?=[A-Z])", " ", spaced)
    return " ".join(spaced.split())


# ─── Items ───────────────────────────────────────────────────────


def item(item_id: str) -> Optional[dict]:
    return _lookup("items", item_id)


def item_name(item_id: str) -> str:
    entry = item(item_id)
    return entry["name"] if entry else humanize(item_id)


def describe_item(item_id: str) -> dict[str, Any]:
    """Everything a list row or tooltip needs, with safe fallbacks."""
    entry = item(item_id) or {}
    return {
        "id": item_id,
        "name": entry.get("name") or humanize(item_id),
        "icon": entry.get("icon", ""),
        "rarity": entry.get("rarity", 0),
        "typeA": entry.get("typeA", ""),
        "typeB": entry.get("typeB", ""),
        "maxStack": entry.get("maxStack", 0),
        "weight": entry.get("weight", 0),
        "description": entry.get("description", ""),
        "known": bool(entry),
    }


def all_items() -> list[dict[str, Any]]:
    """
    The whole item catalogue — every id the game has, not the ones a world holds.

    The distinction is the bug this exists for. The slot editor's autocomplete
    was built from `/api/items`, which reports **what is in the parsed world**,
    so typing any legitimate item nobody on the server happened to own showed
    "not in this world" with no icon. The backend accepted it on preview, having
    always validated against this full catalogue — so the editor was telling
    people their input was wrong and then writing it correctly.

    `id` and `name` both travel because the API speaks ids (`AIcore`) and people
    speak names ("AI Core"), and a catalogue that carries only one of them forces
    every caller to build the other index itself.
    """
    entries = (load().get("items") or {})
    return [
        {
            "id": item_id,
            "name": entry.get("name") or humanize(item_id),
            "icon": entry.get("icon", ""),
            "rarity": entry.get("rarity", 0),
            "typeA": entry.get("typeA", ""),
            "typeB": entry.get("typeB", ""),
            "maxStack": entry.get("maxStack", 0),
            "weight": entry.get("weight", 0),
            # Present only on equipment. The editor uses it to warn *before* a
            # preview that a slot cannot be overwritten without orphaning a
            # DynamicItemSaveData record.
            "hasDurability": bool((entry.get("dynamic") or {}).get("type")),
        }
        for item_id, entry in sorted(entries.items())
    ]


def max_stack(item_id: str) -> int:
    """
    The game's real stack ceiling, or 0 if unknown.

    saveedit currently infers a ceiling from the largest stack present in the
    save. This is the authoritative figure, but swapping it in changes what a
    sort writes, so that is a deliberate change and not a drive-by one.
    """
    entry = item(item_id)
    return int(entry.get("maxStack") or 0) if entry else 0


# ─── Pals ────────────────────────────────────────────────────────


def normalise_species(species_id: str) -> tuple[str, list[str]]:
    """Strip BOSS_/PREDATOR_/etc, returning (species, prefixes_found)."""
    remaining = str(species_id or "")
    found: list[str] = []
    changed = True
    while changed:
        changed = False
        for prefix in _SPECIES_PREFIXES:
            if remaining.upper().startswith(prefix):
                found.append(prefix.rstrip("_"))
                remaining = remaining[len(prefix):]
                changed = True
    return remaining, found


def pal(species_id: str) -> Optional[dict]:
    species, _ = normalise_species(species_id)
    return _lookup("pals", species)


def pal_exact(species_id: str) -> Optional[dict]:
    """
    A species' own entry, **without** stripping `BOSS_` and friends.

    `pal()` normalises, which is right for naming — an alpha Lamball is still
    called Lamball — and wrong for anything that reads the numbers, because the
    prefixed forms carry their own, higher, stat scaling. `BOSS_Alpaca` has hp
    108 where `Alpaca` has 90, and that difference *is* the alpha bonus. Look up
    the base species and the bonus silently disappears; apply a separate boss
    multiplier on top of the base and it gets counted twice.

    Falls back to the normalised lookup, so a form present in a save but absent
    from the tables still resolves to something rather than to nothing.
    """
    return _lookup("pals", species_id) or pal(species_id)


def pal_exp_table() -> dict[str, Any]:
    """
    The game's own level -> EXP table. `{}` if the bundle is unavailable.

    Two columns per level, and picking the wrong one is easy: `PalNextEXP` is
    the Pal curve and `NextEXP` beside it is the *player* curve. They differ
    from level 2 onwards (25 vs 50).
    """
    return load().get("palExpTable") or {}


def pal_name(species_id: str) -> str:
    entry = pal(species_id)
    if entry:
        return entry["name"]
    species, _ = normalise_species(species_id)
    return humanize(species)


def describe_pal(species_id: str) -> dict[str, Any]:
    species, prefixes = normalise_species(species_id)
    entry = pal(species_id) or {}
    return {
        "id": species_id,
        "species": species,
        "name": entry.get("name") or humanize(species),
        "icon": entry.get("icon", ""),
        "elements": entry.get("elements", []),
        "rarity": entry.get("rarity", 0),
        "paldeckNumber": entry.get("zukanIndex", 0),
        "workSuitabilities": entry.get("workSuitabilities", {}),
        "variants": prefixes,
        "known": bool(entry),
    }


def npc_name(npc_id: str) -> str:
    entry = _lookup("npcs", npc_id)
    return entry["name"] if entry else humanize(npc_id)


def character(character_id: str) -> Optional[dict]:
    """
    The record for anything in CharacterSaveParameterMap, Pal or human.

    `pal()` alone answers "is this a known Pal", which is not the same question
    as "is this a known character". On the reference world 100 of the 1,905
    entries are NPCs — guards, merchants, villagers — so treating a Pal-table
    miss as "unrecognised" flags a clean world as full of modded content.
    """
    species, _ = normalise_species(character_id)
    return _lookup("pals", species) or _lookup("npcs", species)


def character_name(character_id: str) -> str:
    """
    Name for anything in CharacterSaveParameterMap.

    That map holds humans as well as Pals — merchants, guards, tower bosses — so
    a Pal-only lookup leaves a good fraction of a real world showing internal IDs
    like `Believer_CrossBow` instead of `Free Pal Alliance Believer`.
    """
    species, _ = normalise_species(character_id)
    entry = _lookup("pals", species) or _lookup("npcs", species)
    return entry["name"] if entry else humanize(species)


# ─── Skills ──────────────────────────────────────────────────────


def passive_name(passive_id: str) -> str:
    entry = _lookup("passives", passive_id)
    return entry["name"] if entry else humanize(passive_id)


def describe_passive(passive_id: str) -> dict[str, Any]:
    entry = _lookup("passives", passive_id) or {}
    return {
        "id": passive_id,
        "name": entry.get("name") or humanize(passive_id),
        "rank": entry.get("rank", 0),
        "icon": entry.get("icon", ""),
        "description": entry.get("description", ""),
        "known": bool(entry),
    }


def skill_name(skill_id: str) -> str:
    """Active skill. Save IDs arrive as `EPalWazaID::PowerBall`."""
    cleaned = str(skill_id or "").split("::")[-1]
    entry = _lookup("activeSkills", cleaned)
    return entry["name"] if entry else humanize(cleaned)


# ─── Technology & structures ─────────────────────────────────────


def technology(tech_id: str) -> Optional[dict]:
    return _lookup("technology", tech_id)


def technology_name(tech_id: str) -> str:
    entry = technology(tech_id)
    return entry["name"] if entry else humanize(tech_id)


def structure_name(structure_id: str) -> str:
    entry = _lookup("structures", structure_id)
    return entry["name"] if entry else humanize(structure_id)


def best_work_suitability(species_id: str) -> Optional[str]:
    """
    The one work type a species is *best* at, from `DT_PalMonsterParameter`.

    **This is the per-species half of the condenser mechanic.** Raising a Pal's
    condenser rank raises its work suitability for this work type only — which
    is why the field is bundled even though the *size* of that increase is in
    none of the game's data files.

    Searched exhaustively 2026-08-05 and recorded so nobody repeats it: all 471
    server-pak DataTables, the `BP_PalGameSetting` CDO, the condenser build
    object's own CDO (pure presentation — visuals, collision, destroy FX), and
    the name tables of all **10,286** server-pak blueprints, which reference
    `BestWorkSuitability` **zero** times. A name table is plainly serialised even
    where properties are not, so that last one is decisive: the logic is in the
    binary, the same wall `elements.py` documents.

    So this returns a *fact* and no arithmetic. `optimise.work_level` still
    reports `base` + `bought` and is knowingly low for condensed Pals until the
    magnitude is measured — see task #74, which carries the sampling plan.

    Uses `pal_exact`-style resolution deliberately **not** applied here: the
    lookup is on the id as stored, then the `BOSS_`-stripped form, matching how
    `workSuitabilities` beside it behaves.

    None means the species has no best work — which is real for the handful with
    an entirely empty work table (Panthalus, Astralym) — or that the id is
    unknown. Both cases mean "do not claim a bonus applies".
    """
    entry = _lookup("pals", species_id)
    if entry is None and species_id:
        for prefix in _SPECIES_PREFIXES:
            if species_id.upper().startswith(prefix):
                entry = _lookup("pals", species_id[len(prefix):])
                break
    return (entry or {}).get("bestWorkSuitability") or None


def region_name(region_id: str) -> str:
    """
    What the game calls a map region — `Grass_1` is "Windswept Island".

    `extract-progression.py` deliberately carried `DT_WorldMapAreaData`'s
    `MsgID` unresolved rather than humanising it, because inventing "Grass 1"
    would have been a second source of truth. This is the game's own answer,
    and it is what turns the save's opaque `FindAreaFlagMap` into "47 of 123
    areas discovered".

    The stored ids carry the `REGION_` prefix off the message id; callers pass
    either form.
    """
    regions = load().get("regions") or {}
    key = region_id[len("REGION_"):] if region_id.upper().startswith("REGION_") else region_id
    index = {k.lower(): v for k, v in regions.items()}
    return index.get(key.lower()) or humanize(key)


def dungeon_name(dungeon_id: str) -> str:
    """The game's name for a dungeon — `Sealed Realm of the Frozen Wings`."""
    dungeons = load().get("dungeons") or {}
    key = dungeon_id[len("NAME_"):] if dungeon_id.upper().startswith("NAME_") else dungeon_id
    index = {k.lower(): v for k, v in dungeons.items()}
    return index.get(key.lower()) or humanize(key)


# ─── World data ──────────────────────────────────────────────────


def effigies() -> list[dict[str, Any]]:
    """
    All 396 effigies, each with world coordinates **and its instance GUID**.

    The GUID is the useful part. A save's `RelicObtainForInstanceFlag` keys on
    exactly these values, so a player's collected set joins directly against
    this list — which is what makes "show me the ones I have not found" possible
    rather than just "here are all of them".

    Extracted from the game pak by `scripts/extract-effigies.py`; every position
    is verified to land in a streaming cell the game ships content for, and
    every effigy the reference world's players had collected (37 of 37) appears
    here. Returns an empty list rather than raising if the bundle is absent, so
    a missing file degrades the map instead of breaking it.
    """
    global _effigies
    if _effigies is not None:
        return _effigies

    try:
        with gzip.open(EFFIGY_PATH, "rt", encoding="utf-8") as f:
            _effigies = json.load(f).get("effigies") or []
    except (OSError, json.JSONDecodeError) as e:
        logger.warning("Effigy data unavailable (%s); the map will omit them", e)
        _effigies = []

    for effigy in _effigies:
        effigy["kindName"] = effigy_kind_name(str(effigy.get("kind") or ""))
    return _effigies


def boss_spawners() -> list[dict[str, Any]]:
    """
    The 90 placed field bosses: species, **level** and world position.

    From `DT_BossSpawnerLoactionData` via `scripts/extract-boss-spawners.py`.
    Levels were documented as unavailable across this project for months — they
    were behind a reader refusal, not absent.

    **Positions are verified, not assumed.** All 90 land on an occupied World
    Partition cell at 25,600 units, with controls at 12,800 (22) and 51,200 (83)
    both worse. The extractor refuses to write if that stops being true.

    Empty list rather than raising when the bundle is absent, like `effigies()`:
    a missing file should cost the layer, not the map.
    """
    global _boss_spawners
    if _boss_spawners is None:
        try:
            with gzip.open(BOSS_SPAWNER_PATH, "rt", encoding="utf-8") as f:
                _boss_spawners = json.load(f).get("bosses") or []
        except (OSError, json.JSONDecodeError) as e:
            logger.warning(
                "Boss spawner data unavailable (%s); the layer will be empty", e
            )
            _boss_spawners = []
    return _boss_spawners


#: How far apart two records of the same field boss may sit and still be the
#: same field boss. **One World Partition cell**, the constant the cell grid is
#: pinned at everywhere else here — chosen because it is already established
#: rather than fitted to this join's own gap, which would be fitting the method
#: to the answer.
_SAME_BOSS = 25600.0

_boss_level_index: Optional[dict[str, list[tuple[float, float, int, str]]]] = None


def _boss_level_lookup() -> dict[str, list[tuple[float, float, int, str]]]:
    global _boss_level_index
    if _boss_level_index is None:
        index: dict[str, list[tuple[float, float, int, str]]] = {}
        for row in boss_spawners():
            species = str(row.get("speciesId") or "")
            if not species:
                continue
            index.setdefault(species, []).append(
                (float(row.get("x") or 0.0), float(row.get("y") or 0.0),
                 int(row.get("level") or 0), str(row.get("spawnerId") or ""))
            )
        _boss_level_index = index
    return _boss_level_index


def boss_level_at(species: str, x: float, y: float) -> Optional[dict[str, Any]]:
    """
    The level of the field boss standing at `(x, y)`, or None.

    **Two extractions of overlapping things, joined on POSITION rather than on
    species.** `worldobjects.json.gz` carries 99 `FBOSS` placements found by
    name-table intersection; `boss_spawners.json.gz` carries 90 rows read out of
    `DT_BossSpawnerLoactionData`, and AGENTS.md records that neither supersedes
    the other. So the popup said "level is on the other layer" — technically
    honest and useless to somebody looking at Silvegis, whose level the game's
    own map shows.

    **The join is measured, and it holds.** Of the 93 placements whose species
    appears in the boss table, **60 sit at a distance of ~0** — byte-identical
    coordinates, the same actor read two ways — and 64 fall inside one cell. The
    control is what makes that evidence: shuffle the species labels across the
    boss rows and the best of 200 trials matches **7**. A drifted or coincidental
    correspondence does not put sixty points on top of each other.

    **Species alone is NOT enough, and the data says why.** `BOSS_GrassGolem` is
    the one species with two levels (55 and 75) — so a species-keyed lookup would
    confidently hand one placement the other's level. It is also the reason
    `remainsIsland_1_GrassGolem_FBOSS` is listed twice, noted in AGENTS.md.

    The 35 placements with no match keep no level rather than borrowing one from
    the same species elsewhere: a second placement of a species genuinely can
    carry a different level, and an inferred number reads exactly like a read one.
    """
    candidates = _boss_level_lookup().get(species or "")
    if not candidates:
        return None
    best = min(candidates, key=lambda c: (c[0] - x) ** 2 + (c[1] - y) ** 2)
    distance = ((best[0] - x) ** 2 + (best[1] - y) ** 2) ** 0.5
    if distance > _SAME_BOSS:
        return None
    return {"level": best[2], "spawnerId": best[3], "distance": round(distance, 1)}


def describe_boss(entry: dict[str, Any]) -> dict[str, Any]:
    """One boss row with its display name and artwork joined on."""
    species = str(entry.get("speciesId") or "")
    info = pal(species) or {}
    return {
        **entry,
        # `pal()` strips the BOSS_ prefix, which is right for naming: an alpha
        # Lamball is still called Lamball. Stats would need `pal_exact`.
        "name": info.get("name") or humanize(species),
        "icon": info.get("icon", ""),
        "elements": info.get("elements") or [],
        "paldeckNumber": info.get("paldeckNumber"),
    }


def work_assign(structure_id: str) -> Optional[dict[str, Any]]:
    """
    Which work a structure needs, from `DT_MapObjectAssignData`.

    Returns None for anything not in the table, and **that is a meaningful
    answer rather than a gap**: the structures absent from it are exactly the
    ones no Pal is ever assigned to. On the reference world 44 of 63 base-placed
    kinds resolve and the 19 that do not are chests, beds, the palbox, the spa,
    walls and the food boxes. `test_work_assign.py` pins that.

    **Case-insensitive**, like every other lookup here: the save spells it
    `Workbench` and the table says `WorkBench`, so an exact match loses a real
    structure without saying so.

    A structure can need more than one kind of work — a farm plot needs Seeding,
    Watering and Collection — so `slots` is a list. Reading only the first
    answers a third of the question and looks complete.
    """
    global _work_assign
    if _work_assign is None:
        try:
            with gzip.open(WORK_ASSIGN_PATH, "rt", encoding="utf-8") as f:
                objects = json.load(f).get("objects") or {}
            # Keyed lowercase on load rather than lowercasing per lookup: this
            # is read once per structure in a per-base walk.
            _work_assign = {str(k).lower(): v for k, v in objects.items()}
        except (OSError, json.JSONDecodeError) as e:
            logger.warning(
                "Work assignment data unavailable (%s); per-structure work "
                "requirements will be unknown", e
            )
            _work_assign = {}
    return _work_assign.get(str(structure_id or "").lower())


def work_assign_available() -> bool:
    """
    Whether the bundle loaded at all.

    Distinct from a structure simply not being in it, which is normal. A caller
    reporting "this base needs no work" must be able to tell the two apart —
    that is the `.catch(() => [])` lesson: an empty answer and a failed load
    must not share a representation.
    """
    work_assign("")
    return bool(_work_assign)


def basecamp() -> dict[str, Any]:
    """
    Base camp levels, illness penalties and worker sanity thresholds.

    Three small tables bundled together because they answer one question — what
    is happening at a base and whether it is coping.

    Empty dict rather than raising when the bundle is absent, like every other
    accessor here: a missing file should cost the panel, not the page.
    """
    global _basecamp
    if _basecamp is None:
        try:
            with gzip.open(BASECAMP_PATH, "rt", encoding="utf-8") as f:
                _basecamp = json.load(f)
        except (OSError, json.JSONDecodeError) as e:
            logger.warning(
                "Base camp data unavailable (%s); worker caps and illness "
                "detail will be missing", e
            )
            _basecamp = {}
    return _basecamp


def base_worker_cap(level: int) -> Optional[int]:
    """
    How many Pals a base of this level may hold **in an unmodified game**.

    THIS IS NOT THE CAP ON ANY PARTICULAR SERVER, IT IS NOT A MAXIMUM, AND IT IS
    NOT A FALLBACK. Two things override it:

    1. **`BaseCampWorkerMaxNum` in `PalWorldSettings.ini`** — a server setting.
       The shipped default is **15** against this table's 30, and a real server
       in use runs 25 workers and 5 bases per guild where the table says 30 and
       4. It is over in one direction and under in the other, which is what
       proves the table bounds nothing. `server_worker_cap()` reads the real
       value and returns None rather than substituting this one.

    2. **The base's level**, which gates how much of the cap is unlocked — a
       level-1 base holds one Pal whatever the server allows.

    And the catch that makes (2) unusable today: **base level is not in the
    save.** `BaseCampSaveData.RawData` carries id, name, state, transform,
    area_range, group and the owning palbox's instance id, and nothing else; the
    palbox's own model and concrete model carry no level either. So this function
    has no caller that can supply an argument to it yet. It is bundled because
    the table is real and the level will turn up somewhere (`unknown_bytes` on
    the palbox model is the obvious place to look next), not because anything
    uses it.

    Returns None for a level the table does not cover rather than clamping to the
    nearest — "cap unknown" and "cap is 30" are different answers.
    """
    for row in basecamp().get("levels") or []:
        if int(row.get("level") or 0) == int(level or 0):
            return int(row.get("workerMax") or 0)
    return None


# The INI keys that actually govern. The DataTable is a *default*, not a bound —
# see `server_limit`.
WORKER_CAP_SETTING = "BaseCampWorkerMaxNum"
BASES_PER_GUILD_SETTING = "BaseCampMaxNumInGuild"
# **A guild's member cap is a SETTING, not a game constraint.** It reads like a
# rule of the game and is not: `GuildPlayerMaxNum` sits in the INI beside the
# base and worker caps, so an operator can run guilds of 4 or 100 and no bundled
# table bounds it. Same authority rule as the two above.
GUILD_MEMBER_CAP_SETTING = "GuildPlayerMaxNum"
BASES_TOTAL_SETTING = "BaseCampMaxNum"


def server_limit(setting: str) -> Optional[int]:
    """
    One of this server's own limits, read from its INI.

    **THE INI IS THE ONLY AUTHORITY AND THE BUNDLED TABLE BOUNDS NOTHING.** That
    is measured, not cautious: `DT_BaseCampLevelData` tops out at 4 bases per
    guild and 30 workers, and a real server in use runs **5 bases and 25
    workers** — over the table in one direction and under it in the other. So the
    table cannot be used as a ceiling, a floor, or a fallback. It describes an
    unmodified game and nothing else.

    Nor is there a hard maximum to fall back on: `BaseCampMaxNum` defaults to 128
    and is itself a setting. Every one of these numbers is the operator's.

    None when the INI cannot be read, which is the *common* case — the normal
    deployment mounts only the save path. **None means "not known", never
    "unlimited" and never "use the game's value"**: a caller must show no
    denominator rather than a wrong one, the same way `iniwatch` treats
    `unknown` as a real answer rather than as "safe".
    """
    try:
        import settings_ini

        options = settings_ini.read_ini()
    except Exception as e:  # noqa: BLE001 - an unreadable INI is normal here
        logger.debug("Cannot read %s from the INI (%s)", setting, e)
        return None

    entry = (options.get("options") or {}).get(setting)
    if isinstance(entry, dict):
        entry = entry.get("value")
    try:
        return int(entry)
    except (TypeError, ValueError):
        return None


def server_worker_cap() -> Optional[int]:
    """How many Pals a base may hold on **this** server."""
    return server_limit(WORKER_CAP_SETTING)


def server_bases_per_guild() -> Optional[int]:
    """How many bases a guild may build on **this** server."""
    return server_limit(BASES_PER_GUILD_SETTING)


def server_guild_member_cap() -> Optional[int]:
    """
    How many players a guild may hold on **this** server.

    `GuildPlayerMaxNum`, and it belongs here rather than anywhere near the
    bundled data: it is the operator's number. The game's own difficulty presets
    all ship 20, which makes 20 look like a rule and is only a default.

    `None` means not known — the usual case, since most deployments mount only
    the save path — and a caller must then show no denominator rather than a
    guessed one.
    """
    return server_limit(GUILD_MEMBER_CAP_SETTING)


def illness(sick_id: str) -> Optional[dict[str, Any]]:
    """
    What one illness costs: work speed, move speed, satiety, and the chance the
    palbox clears it per hour.

    `EffectiveItemRank` travels but is deliberately NOT resolved to a medicine
    item here. Which item clears which rank is unverified, and naming one would
    be the sort of mechanic claim `basesupply` refuses to make.
    """
    key = str(sick_id or "").lower()
    for row in basecamp().get("illnesses") or []:
        if str(row.get("id") or "").lower() == key:
            return row
    return None


def worker_sanity_thresholds() -> list[dict[str, Any]]:
    """
    The sanity levels at which a worker misbehaves, highest first.

    **These are not the same number as `main.LOW_SANITY`.** That is 50, from
    `FriendshipPoint_AutoIncrementRequireSanity` — the sanity a Pal needs to keep
    gaining *trust*. A worker starts taking short breaks at 85 and has stopped
    being useful well before 50, so a panel warning at 50 is answering a
    different question from the one it appears to answer.
    """
    return basecamp().get("workerEvents") or []


def economy() -> dict[str, Any]:
    """
    Recipes, Pal drops, loot tables, shops, food effects and production yields.

    From the server pak via `scripts/extract-economy.py`. Empty dict when the
    bundle is absent, like every accessor here.
    """
    global _economy
    if _economy is None:
        try:
            with gzip.open(ECONOMY_PATH, "rt", encoding="utf-8") as f:
                _economy = json.load(f)
        except (OSError, json.JSONDecodeError) as e:
            logger.warning(
                "Economy data unavailable (%s); recipes, drops and shop stock "
                "will be missing", e
            )
            _economy = {}
    return _economy


def recipes_for(item_id: str) -> list[dict[str, Any]]:
    """
    **Every** way to craft an item: materials, counts and work amount.

    The bundle used to key one recipe per product, which threw away fifteen rows
    — including twelve of the thirteen ways to get a Paldium Fragment, since
    dismantling each kind of Pal Sphere is its own row. That is survivable for
    "how do I make X" and wrong for "where does X come from", which is the
    question `itemsource` exists to answer.

    Which *bench* crafts it is not here, and not anywhere: `WorkableAttribute`
    is present on every recipe row and is 0 on all of them.
    """
    return (economy().get("recipes") or {}).get(str(item_id or "")) or []


def recipe(item_id: str) -> Optional[dict[str, Any]]:
    """The cheapest single recipe for an item, or `None`. See `recipes_for`."""
    rows = recipes_for(item_id)
    return rows[0] if rows else None


def used_in_recipes(item_id: str) -> list[dict[str, Any]]:
    """
    What this item is a *material* for — the reverse of `recipes_for`.

    Scans, like `dropped_by`, and for the same reason: ~1,400 recipes with at
    most five materials each is a few thousand comparisons against a reverse
    index that would need invalidating alongside the forward one.
    """
    wanted = str(item_id or "").lower()
    if not wanted:
        return []
    out = []
    for rows in (economy().get("recipes") or {}).values():
        for row in rows:
            for material in row.get("materials") or []:
                if str(material.get("itemId") or "").lower() == wanted:
                    out.append({
                        "recipeId": row.get("recipeId"),
                        "productId": row.get("productId"),
                        "count": row.get("count"),
                        "needs": material.get("count"),
                    })
    out.sort(key=lambda r: (r.get("needs") or 0, str(r.get("productId"))))
    return out


def found_in_loot(item_id: str) -> list[dict[str, Any]]:
    """
    Which loot fields — chests, dungeon rooms, field drops — contain this item.

    **`weight` is relative within one field's slot, and nothing else.** Two
    fields' weights are not comparable and nothing here says how often a field is
    rolled, so this is honest as "which chests" and dishonest as a drop rate.
    Same constraint `habitats.json.gz` carries as `weightIsWithinGroup`.
    """
    wanted = str(item_id or "").lower()
    if not wanted:
        return []
    out = []
    for field, rows in (economy().get("lottery") or {}).items():
        total = {}
        for row in rows:
            total[row.get("slot")] = total.get(row.get("slot"), 0.0) + float(
                row.get("weight") or 0.0
            )
        for row in rows:
            if str(row.get("itemId") or "").lower() != wanted:
                continue
            slot_total = total.get(row.get("slot")) or 0.0
            out.append({
                "field": field,
                "slot": row.get("slot"),
                "weight": row.get("weight"),
                # The share of its own slot, which IS comparable — it is the
                # chance this item fills that slot when the field is rolled.
                "slotShare": (
                    round(float(row.get("weight") or 0.0) / slot_total, 4)
                    if slot_total else None
                ),
                "min": row.get("min"),
                "max": row.get("max"),
                "grade": row.get("grade"),
            })
    out.sort(key=lambda r: (-(r.get("slotShare") or 0), r["field"]))
    return out


def sold_by(item_id: str) -> list[dict[str, Any]]:
    """Which merchants stock this item, and at what price override."""
    wanted = str(item_id or "").lower()
    if not wanted:
        return []
    out = []
    for shop, rows in (economy().get("shops") or {}).items():
        for row in rows:
            if str(row.get("itemId") or "").lower() == wanted:
                out.append({"shop": shop, **row})
    out.sort(key=lambda r: r["shop"])
    return out


def produced_by(item_id: str) -> list[dict[str, Any]]:
    """Which base structures yield this item on their own, and how fast."""
    wanted = str(item_id or "").lower()
    if not wanted:
        return []
    return [
        {"structureId": key, **row}
        for key, row in sorted((economy().get("production") or {}).items())
        if str(row.get("productId") or "").lower() == wanted
    ]


def technology_unlocks(tech_id: str) -> Optional[dict[str, Any]]:
    """
    What a technology unlocks, and what must be researched before it.

    Distinct from `technology()`, which is the *catalogue* entry — name, icon,
    cost, tier. This is the economy bundle's row and carries the two columns the
    catalogue does not: `unlocksRecipes` and `requiresTechnology`.
    """
    return (economy().get("techUnlocks") or {}).get(str(tech_id or ""))


def unlocked_by(recipe_id: str) -> list[dict[str, Any]]:
    """
    Which technology unlocks a given recipe **row**.

    Keyed on `recipeId`, not on the product — a product with several recipes can
    have them unlocked by different technologies, which is the whole reason the
    row id is carried.
    """
    wanted = str(recipe_id or "").lower()
    if not wanted:
        return []
    return [
        tech for tech in (economy().get("techUnlocks") or {}).values()
        if any(str(r).lower() == wanted for r in tech.get("unlocksRecipes") or [])
    ]


def technology_chain(tech_id: str) -> list[str]:
    """
    A technology and everything that must be researched before it, in order.

    Guarded against a cycle rather than trusted not to have one: the data is the
    game's and the walk is unbounded, so a self-referential row would hang the
    request rather than raise.
    """
    chain: list[str] = []
    seen: set[str] = set()
    current = str(tech_id or "")
    while current and current not in seen:
        seen.add(current)
        entry = technology_unlocks(current)
        if entry is None:
            break
        chain.append(current)
        current = str(entry.get("requiresTechnology") or "")
    chain.reverse()
    return chain


def drops_for(species_id: str) -> list[dict[str, Any]]:
    """
    What a species drops, by level band.

    **`levelFrom` is a band, not a level.** The column holds only 0, 10, 20 … 80,
    so a row covers "level 30-39". Interpolating between bands would be
    inventing numbers the game does not have.

    Case-insensitive, and `BOSS_`-prefixed variants have their own tables — an
    alpha drops differently from the ordinary form, so this does *not* strip the
    prefix the way `pal()` does.
    """
    table = economy().get("drops") or {}
    key = str(species_id or "")
    if key in table:
        return table[key]
    lowered = key.lower()
    for name, rows in table.items():
        if name.lower() == lowered:
            return rows
    return []


def dropped_by(item_id: str) -> list[dict[str, Any]]:
    """
    Which species drop this item, with rates — the reverse lookup, and the one
    a player actually asks ("where do I get Leather?").

    Scans rather than indexes: ~890 species with a handful of bands each is a
    few thousand comparisons, and building a reverse index would need
    invalidating alongside the forward one for no measurable gain.
    """
    wanted = str(item_id or "").lower()
    if not wanted:
        return []
    out = []
    for species, bands in (economy().get("drops") or {}).items():
        for band in bands:
            for entry in band.get("items") or []:
                if str(entry.get("itemId") or "").lower() == wanted:
                    out.append({
                        "speciesId": species,
                        "levelFrom": band.get("levelFrom"),
                        **entry,
                    })
    out.sort(key=lambda r: (-float(r.get("rate") or 0), r["speciesId"]))
    return out


def food_effect(item_id: str) -> Optional[dict[str, Any]]:
    """What a cooked dish does, and for how long."""
    return (economy().get("food") or {}).get(str(item_id or ""))


def spawns() -> dict[str, Any]:
    """
    Spawn points with verified world positions, and the roster at each.

    Supersedes `habitats.py`'s name-table intersection: 482 species with real
    level ranges and weights against that workaround's 348 and its explicitly
    narrow "references this species" claim.

    Positions are verified, not assumed — all 8,253 land on an occupied World
    Partition cell at 25,600 units, with both wrong cell sizes doing worse.
    """
    global _spawns
    if _spawns is None:
        try:
            with gzip.open(SPAWNS_PATH, "rt", encoding="utf-8") as f:
                _spawns = json.load(f)
        except (OSError, json.JSONDecodeError) as e:
            logger.warning(
                "Spawn data unavailable (%s); the spawn layer will be empty", e
            )
            _spawns = {}
    return _spawns


def spawns_for(species_id: str) -> list[dict[str, Any]]:
    """
    Every place a species spawns, with its level range there.

    Joins rosters to placements by spawner name, so a result is a real world
    position and not a region shading. Case-insensitive, and the `BOSS_` prefix
    is **not** stripped: an alpha spawns at its own points, not its base form's.

    Returns the placement rows enriched with the roster entry that named the
    species, because "where" without "at what level" is half an answer.
    """
    data = spawns()
    rosters = data.get("spawners") or {}
    wanted = str(species_id or "").lower()
    if not wanted:
        return []

    # Which spawners name it, and on what terms.
    matching: dict[str, dict[str, Any]] = {}
    for name, variants in rosters.items():
        for variant in variants:
            for entry in variant.get("entries") or []:
                if str(entry.get("speciesId") or "").lower() != wanted:
                    continue
                current = matching.get(name)
                # Keep the widest level range across variants of one spawner.
                if current is None:
                    matching[name] = {
                        "levelMin": entry["levelMin"],
                        "levelMax": entry["levelMax"],
                        "weight": variant.get("weight", 0.0),
                        "onlyTime": variant.get("onlyTime", ""),
                        "onlyWeather": variant.get("onlyWeather", ""),
                    }
                else:
                    current["levelMin"] = min(current["levelMin"], entry["levelMin"])
                    current["levelMax"] = max(current["levelMax"], entry["levelMax"])

    if not matching:
        return []

    return [
        {**placement, **matching[placement["spawnerName"]]}
        for placement in (data.get("placements") or [])
        if placement.get("spawnerName") in matching
    ]


def moves() -> dict[str, Any]:
    """Move data, learn lists, egg-move pools and unique breeding combinations."""
    global _moves
    if _moves is None:
        try:
            with gzip.open(MOVES_PATH, "rt", encoding="utf-8") as f:
                _moves = json.load(f)
        except (OSError, json.JSONDecodeError) as e:
            logger.warning("Move data unavailable (%s)", e)
            _moves = {}
    return _moves


def species_moves(species_id: str) -> dict[str, Any]:
    """
    Every move a species can have, and **how each is obtained**.

    Three sources, kept apart because the distinction is the whole point:

    - `levelUp` — `DT_WazaMasterLevel`, with the level each is learned at.
    - `egg` — `DT_WazaMasterTamago`. **These can ONLY be inherited by breeding**,
      which is what decides whether a breeding target is worth chasing at all. A
      Pal that already exists cannot be taught one.
    - `active` — what this species starts with, from the bundled catalogue.

    None of this was read by anything before 2026-08-05. The Pal view showed the
    three moves a Pal has equipped and said nothing about what it *could* have.

    Resolved through the same prefix-stripping every other species lookup here
    uses, so an alpha resolves to its base species — an alpha Lamball learns what
    a Lamball learns.

    **EGG POOLS ARE KEYED ON THE `BOSS_` FORM. ALL 283 OF THEM.** Not some: the
    table contains zero unprefixed keys. A first attempt looked the species up
    exactly and fell back to the stem, reasoning that `BOSS_Carbunclo`'s pool
    was its own and folding it into `Carbunclo` would report moves the base form
    could not inherit. That is backwards — the alpha entry IS where the game
    stores the species' egg moves, so `Carbunclo` reported **0 egg moves when it
    has 9**, silently, on every ordinary Pal in the game.

    The tell was the shape: a feature that works only for alphas is not a
    feature, and 283 pools against 753 forms does not divide into "some species
    have them".
    """
    data = moves()
    egg_pools = data.get("eggMoves") or {}
    learn_lists = data.get("learned") or {}

    def resolve(table: dict, exact_first: bool) -> Any:
        index = {k.lower(): v for k, v in table.items()}
        if exact_first:
            hit = index.get(str(species_id).lower())
            if hit is not None:
                return hit
        stem = species_id
        for prefix in _SPECIES_PREFIXES:
            if stem.upper().startswith(prefix):
                stem = stem[len(prefix):]
                break
        return index.get(stem.lower())

    level_up = resolve(learn_lists, exact_first=True) or []
    # Try `BOSS_<stem>` first, because that is the only form the table uses.
    egg = resolve(egg_pools, exact_first=True)
    if not egg:
        stem = species_id
        for prefix in _SPECIES_PREFIXES:
            if stem.upper().startswith(prefix):
                stem = stem[len(prefix):]
                break
        egg = {k.lower(): v for k, v in egg_pools.items()}.get(f"boss_{stem}".lower())
    egg = egg or []

    def described(move_id: str) -> dict[str, Any]:
        info = move(move_id) or {}
        return {
            "id": move_id,
            "name": skill_name(move_id),
            "element": info.get("element") or "",
            "power": info.get("displayPower", info.get("power", 0)),
            "cooldown": info.get("cooldown", 0),
            "category": info.get("category") or "",
        }

    return {
        "levelUp": [
            {**described(str(row.get("moveId") or "")), "level": int(row.get("level") or 0)}
            for row in level_up
            if row.get("moveId")
        ],
        # Flagged, not merely listed. A caller must be able to say "breed for
        # this" rather than presenting an unobtainable move as available.
        "egg": [{**described(str(m)), "eggOnly": True} for m in egg],
        "eggCount": len(egg),
    }


def move(move_id: str) -> Optional[dict[str, Any]]:
    """
    One move: element, category, power, cooldown and range.

    **Bare ids, no `EPalWazaID::` prefix.** The API speaks bare ids everywhere
    and `charedit` re-attaches the prefix only on write; the prefix is stripped
    once at extraction, so a caller passing a prefixed id gets nothing. Handled
    here rather than left as a trap.
    """
    table = moves().get("moves") or {}
    key = str(move_id or "")
    return table.get(key.rsplit("::", 1)[-1] if "::" in key else key)


def learned_moves(species_id: str) -> list[dict[str, Any]]:
    """Which moves a species learns by levelling, and at what level."""
    return (moves().get("learned") or {}).get(str(species_id or "")) or []


def egg_moves(species_id: str) -> list[str]:
    """
    Which moves a species can inherit through an egg.

    This is the reason people breed past the species chart, and nothing in the
    dashboard has ever surfaced it.
    """
    return (moves().get("eggMoves") or {}).get(str(species_id or "")) or []


def unique_combos() -> list[dict[str, Any]]:
    """
    The game's own special breeding pairs, keyed on **tribes** with the member
    species resolved alongside.

    **Gender is load-bearing on exactly one pair.** 256 of 258 rows say "either
    gender"; the two that do not are CatMage x FoxMage, which yields
    `FoxMage_Dark` or `CatMage_Fire` depending on which parent is which. Any
    consumer keying on an unordered pair can only hold one of those — which is
    precisely what palcalc's table does, and the only thing it gets wrong.
    """
    return moves().get("uniqueCombos") or []


def progression() -> dict[str, Any]:
    """Relic ranks, stat elixirs, region ids, quest positions and dungeons."""
    global _progression
    if _progression is None:
        try:
            with gzip.open(PROGRESSION_PATH, "rt", encoding="utf-8") as f:
                _progression = json.load(f)
        except (OSError, json.JSONDecodeError) as e:
            logger.warning("Progression data unavailable (%s)", e)
            _progression = {}
    return _progression


def relic_rank(relic_type: str, relics_spent: int) -> Optional[dict[str, Any]]:
    """
    What a number of relics spent on ONE statue line buys, and what the next rank
    costs.

    The map has shown all 396 effigies and which a player found since the layer
    shipped, and has never said what finding them *did*. This is that.

    **`RequiredRelicNum` is the cost of that rank, not a running total**, and
    reading it as a threshold gets the answer badly wrong. `HungerReduction`
    charges 1 relic for each of its 20 ranks; a cumulative reading would say rank
    20 costs one relic. `MoveSpeed` runs 1, then 3 for seventy-eight ranks, then
    4 — 287 relics for all 92. So the running total is summed here.

    **`EffectRate` IS already cumulative** — the total effect at that rank, not
    an increment. HungerReduction reads 2.5, 5.0, 7.5 across its first three.
    The two adjacent columns work in opposite ways, which is exactly the sort of
    thing to state rather than leave to a reader.

    **`CapturePower` is the one line with no rate at all**: all 15 of its ranks
    are 0.0 while the other twelve types carry real values. Its effect is
    evidently expressed somewhere other than this column, so a caller must not
    render "+0%" — `hasEffectRate` says which case it is.
    """
    ranks = (progression().get("relicRanks") or {}).get(str(relic_type or ""))
    if not ranks:
        return None

    spent = max(0, int(relics_spent or 0))
    has_rate = any(r["effectRate"] for r in ranks)

    running = 0
    current = {"rank": 0, "effectRate": 0.0, "resetCost": 0}
    for row in ranks:
        running += row["requiredRelics"]
        if running > spent:
            return {
                **current,
                "relicsSpent": spent,
                "hasEffectRate": has_rate,
                "nextRank": row["rank"],
                "relicsToNext": running - spent,
                "totalToMax": sum(r["requiredRelics"] for r in ranks),
            }
        current = row

    return {
        **current,
        "relicsSpent": spent,
        "hasEffectRate": has_rate,
        "nextRank": None,
        "relicsToNext": 0,
        "totalToMax": sum(r["requiredRelics"] for r in ranks),
    }


def relic_types() -> list[str]:
    return sorted(progression().get("relicRanks") or {})


def quest_location(quest_id: str) -> Optional[dict[str, Any]]:
    """Where a quest happens. `range` is -1 on most, meaning no radius."""
    return (progression().get("quests") or {}).get(str(quest_id or ""))


def area_ids() -> dict[str, str]:
    """
    Region id -> its text-table key.

    **Not display names.** `MsgID` is `REGION_Desert_1`, a key into the
    localisation tables, and humanising it here would create a second source of
    truth against them. 123 regions is still enough to turn `areasFound`'s
    opaque flag map into "47 of 123".
    """
    return progression().get("areas") or {}


def _bundle(name: str, path: str, cache_attr: str) -> dict[str, Any]:
    """Load-once helper for the small reference bundles."""
    cached = globals().get(cache_attr)
    if cached is None:
        try:
            with gzip.open(path, "rt", encoding="utf-8") as f:
                cached = json.load(f)
        except (OSError, json.JSONDecodeError) as e:
            logger.warning("%s data unavailable (%s)", name, e)
            cached = {}
        globals()[cache_attr] = cached
    return cached


def raid_bosses() -> dict[str, Any]:
    """
    The altar-summoned raid bosses: what summons each, at what level, what it
    drops, and the egg weights.

    **These have no world position and none must be invented.** `boss_spawners`
    carries 90 *placed* field bosses and zero `RAID_` ids, which is correct
    rather than a gap — a table of locations has nothing to say about something
    summoned at an altar. A map marker for one would be the
    `BP_LevelObject_TowerLockBarrier` mistake exactly.

    **Count forms, not rows.** A summon row's `InfoList` can hold more than one
    boss, and row-counting is what briefly turned 90 field bosses into "159".
    """
    return _bundle("Raid boss", RAIDBOSS_PATH, "_raidbosses").get("bosses") or {}


def invaders() -> dict[str, Any]:
    """
    Base raid groups, their biomes, grade bands and loot.

    **`gradeMeaningKnown` is False and that is load-bearing.** `InvadeGradeMin`
    and `Max` bound a raid to a "grade", and nothing establishes what a grade is
    in save terms — base level, guild level and player level are all plausible.
    So this is a static reference table, and a caller must not turn it into
    "your base will be raided by X". Inventing that mapping is the guess
    `basesupply` refuses to make.
    """
    return _bundle("Invader", INVADERS_PATH, "_invaders")


def world_presets() -> dict[str, Any]:
    """
    The game's own difficulty presets, as Pocketpair sets them.

    A cross-check on `backend/presets.py`'s hand-made ones rather than an
    automatic replacement: `DefaultPalWorldSettings.ini` says which settings
    exist and this says what a difficulty does to them, so the two together are
    two sources where there was one.
    """
    return _bundle("World preset", WORLDPRESETS_PATH, "_worldpresets")


def game_setting(name: str, default: Any = None) -> Any:
    """
    One of Pocketpair's own tuning constants, from `BP_PalGameSetting`.

    347 of them, decoded from the Blueprint's class-default object by
    `scripts/extract-game-settings.py` — damage rates, sanity and hunger
    thresholds, capture rates, base-camp ranges. This is the answer to "surely
    that number is in the files somewhere", which it usually is.

    THE DECODE VERIFIES ITSELF: `CharacterMaxLevel` comes out 80 and
    `CharacterMaxRank` 5, two constants this project already held from sources
    that explicitly could not be checked against the install. A misaligned walk
    does not land two independently-known values in the right places.

    Case-sensitive, unlike the id lookups here — these are UPROPERTY names with
    one fixed spelling rather than ids three files disagree about.
    """
    global _game_settings
    if _game_settings is None:
        try:
            with gzip.open(GAME_SETTINGS_PATH, "rt", encoding="utf-8") as f:
                _game_settings = json.load(f)
        except (OSError, json.JSONDecodeError) as e:
            logger.warning(
                "Game settings unavailable (%s); callers fall back to their own "
                "documented defaults", e,
            )
            _game_settings = {}
    value = _game_settings.get(name)
    return default if value is None else value


def passive_effects(passive_id: str) -> Optional[dict[str, Any]]:
    """
    The *numeric* effects of one passive skill, or None if it is not bundled.

    The `passives` section of `gamedata.json.gz` carries a **sentence** —
    "Attack +5%" — which is right for showing a player and useless for computing
    anything. This is `DT_PassiveSkill_Main` out of the server pak, extracted by
    `scripts/extract-passive-effects.py`:

        {"rank": 4,
         "effects": [{"type": "ShotAttack", "value": 20.0, "target": "ToSelf"},
                     {"type": "Defense",    "value": 20.0, "target": "ToSelf"}],
         "invoke": ["InvokeAlways"], "lotteryWeight": 10, "element": ""}

    VERIFIED AGAINST THE GAME'S OWN PROSE: of the 1,897 bundled passives, 1,754
    have a numeric English description and **1,754 match**, on 5 exceptions —
    four of which are the PST archive's descriptions failing to substitute their
    own `{EffectValue1}` placeholder, so the table is right and the sentence is
    broken. The remaining one (`FullStomach_Down_1_BossDefeat`, prose "+10.0%
    slower" against a stored -1.0) is a real disagreement and is not resolved.

    Case-insensitive like every other lookup here, for the reason the module
    docstring gives.
    """
    global _passive_effects
    if _passive_effects is None:
        try:
            with gzip.open(PASSIVE_EFFECT_PATH, "rt", encoding="utf-8") as f:
                raw = json.load(f)
            _passive_effects = {str(k).lower(): v for k, v in raw.items()}
        except (OSError, json.JSONDecodeError) as e:
            # Degrade rather than raise: without this bundle a stat simply
            # carries no passive term, which is exactly what it did before the
            # bundle existed. A missing file must not take out /api/pals.
            logger.warning(
                "Passive effect data unavailable (%s); stats will omit the "
                "passive term", e,
            )
            _passive_effects = {}
    return _passive_effects.get(str(passive_id or "").lower())


def effigy_kind_name(kind: str) -> str:
    """
    A blueprint class like `BP_LevelObject_Relic_SheepBall` -> "Lamball Effigy".

    THE SUFFIX IS A SPECIES ID, WHICH IS WHY THIS IS NOT A STRING TIDY-UP.
    The map's generic `prettyClass` helper turned these into "Relic Sheep Ball"
    and "BP Relic Object" — de-underscored game-file names shown to players in
    the effigy filter list. Splitting the words is not the same as knowing what
    they mean: `SheepBall` is the internal id for **Lamball**, and only
    `gamedata.pal_name` knows that.

    Resolution is deliberately through `pal_name`, so the case-insensitivity
    applies. The upstream ids are inconsistently capitalised — the extraction
    yields `SheepBall` while the Pal table spells it `Sheepball` — and an exact
    match would silently fall through to the raw name for exactly the entries
    this exists to fix.

    Unrecognised suffixes fall back to a humanised form rather than failing.

    **THE RULE IS VERIFIED AGAINST THE GAME'S OWN ITEM NAMES, NOT MERELY
    PLAUSIBLE.** The catalogue ships thirteen effigy items — `Relic` plus
    `Relic_01`..`Relic_12` — and the suffix rule reproduces **9 of 9** of the
    placed classes' names exactly: `…_IceCrocodile` gives "Munchill Effigy",
    which is what `Relic_03` is called. Building a name out of a class-name
    suffix is the kind of thing that reads right and is wrong, so the agreement
    is the evidence rather than the reasoning.

    **The two unsuffixed classes were rendering as bare "Effigy" — 155 of 396,
    which is why they read as data that had failed to load.** They are the plain
    relic, and the game's own name for the plain relic is `Relic` -> "Lifmunk
    Effigy". Resolved through the catalogue rather than hardcoded, so a
    localisation change carries and a missing bundle degrades to "Effigy"
    instead of to a stale English string.

    Three catalogue entries — Lunaris, Relaxaurus and Mimog — have no placed
    class at all. Not a gap here: nothing in the world references them.
    """
    if not kind:
        return "Effigy"

    for prefix in ("BP_LevelObject_Relic_", "BP_RelicObject_"):
        if kind.startswith(prefix):
            species = kind[len(prefix):]
            return f"{pal_name(species)} Effigy" if species else "Effigy"

    if kind in ("BP_LevelObject_Relic", "BP_RelicObject"):
        plain = item_name("Relic")
        # `item_name` echoes the id back when the catalogue has no row, and
        # "Relic" is not a name to show anybody.
        return plain if plain and plain != "Relic" else "Effigy"
    return f"{humanize(kind)} Effigy"


def fast_travel_kind(name: str) -> str:
    """
    `tower`, `watchtower` or `travel` for one fast-travel point.

    **The tower bosses are already in this table and nothing said so.** All 174
    points rendered as one identical gold marker, so "where are the towers" had
    no answer on a map that was in fact showing all eight of them — the eight
    named `… Tower Entrance`. Splitting the layer by kind was the fix; extracting
    anything new from the pak was not needed and would have been the wrong tree.

    Classified from the localized name rather than from an id, because the name
    is the only field that distinguishes them — the keys are opaque hex. That
    means this is **English-dependent**, and it fails to the safe side: an
    unrecognised name is a plain travel point, which is what every point was
    before this existed.

    The distinction matters because they are different things: a Tower Entrance
    is a boss arena you clear once, a Watchtower is scenery with a statue at the
    bottom, and neither is the other.
    """
    lowered = name.lower()
    if lowered.endswith("tower entrance"):
        return "tower"
    if "watchtower" in lowered:
        return "watchtower"
    return "travel"


def fast_travel_points() -> list[dict[str, Any]]:
    """
    All 174 fast-travel points with world coordinates and localized names.

    Coordinates share the save's world space, so they feed the existing map
    transform unchanged. Covers both landmasses — 17 of these sit on the World
    Tree side.

    Measured split: **8 tower entrances, 22 watchtowers, 144 ordinary points** —
    and the eight are exactly Palworld's eight tower bosses, which is the check
    that the name rule is picking out the right thing rather than merely
    something.
    """
    return [
        {"key": key, "kind": fast_travel_kind(str(value.get("name") or "")), **value}
        for key, value in sorted(load().get("fastTravel", {}).items())
    ]


def fast_travel_name(point_id: str) -> str:
    entry = _lookup("fastTravel", point_id)
    return entry["name"] if entry else humanize(point_id)


def work_suitabilities() -> list[dict[str, Any]]:
    return load().get("workSuitability", [])


# ─── Reference totals ────────────────────────────────────────────


def totals() -> dict[str, Any]:
    """
    Exact Palworld 1.0 figures, computed from the game's own data tables.

    These replace the previously web-sourced estimates. Notably: 1,413 ordinary
    technology points across 537 technologies, and 185 ancient technology points
    across 51 boss technologies.
    """
    return dict(load().get("totals", {}))


def npcs() -> dict[str, Any]:
    """
    Every placed NPC in the world, named — merchants, villagers, hunters, police.

    From `scripts/extract-npcs.py`, which reads a spawner actor's **tagged
    properties** out of the server pak's world cells. That was documented as
    impossible (`upackage.py`: "property values are not [serialised plainly]"),
    and it is — in the *client* pak. The server pak's cells are tagged, so a
    placement says which NPC it spawns and at what level.

    Empty dict when the bundle is absent, like every accessor here.
    """
    global _npcs
    if _npcs is None:
        try:
            with gzip.open(NPCS_PATH, "rt", encoding="utf-8") as f:
                _npcs = json.load(f)
        except (OSError, json.JSONDecodeError) as e:
            logger.warning(
                "NPC data unavailable (%s); the NPC map layers will be empty", e
            )
            _npcs = {}
    return _npcs


def npc_placements(role: Optional[str] = None) -> list[dict[str, Any]]:
    """
    Placed NPCs, optionally one role, each with a display name resolved.

    **Three places a name can come from, in order**, because the game does not
    put them all in one:

    1. `DT_UniqueNPC` via the placement's `UniqueName` — the real thing, and the
       only one that gives "Black Marketeer" rather than "DarkTrader".
    2. the character tables via `characterId`, for the generic types
       (`PalDealer`, `Hunter_Rifle`) that have no unique row.
    3. `humanize()`, so a name is never blank and never raw markup.

    Resolved here rather than at extraction time so a rebuilt `gamedata.json.gz`
    improves these names without re-reading a 4.8 GB pak.
    """
    out = []
    for entry in (npcs().get("placements") or []):
        if role and entry.get("role") != role:
            continue
        name = entry.get("name") or ""
        if not name:
            character = str(entry.get("characterId") or "")
            name = character_name(character) if character else ""
        row = dict(entry)
        if not name:
            # Last resort: the spawner class, with its boilerplate stripped.
            # Humanising it raw gives "BP Mono NPCSpawner Boss Base Male
            # Trader02", which is worse than the id it came from.
            fallback = str(
                entry.get("uniqueId") or entry.get("characterId") or entry.get("cls") or ""
            )
            fallback = re.sub(
                r"^BP_(Mono)?NPCSpawner(BossBase)?_?|^BP_NPCCampSpawner_?|^BP_OilrigNPCSpawner_?",
                "", fallback,
            )
            name = humanize(fallback) if fallback else "Unnamed NPC"
        row["name"] = name
        out.append(row)
    return out


def npc_roles() -> dict[str, str]:
    """`{role: label}` for the layer switches. Empty when the bundle is absent."""
    return npcs().get("roleLabels") or {}


GUILD_PATH = os.environ.get(
    "GUILD_DATA_PATH",
    os.path.join(os.path.dirname(os.path.abspath(__file__)), "data", "guild.json.gz"),
)


def guild_roles() -> dict[str, Any]:
    """
    Guild rank and permission names, from the game's own UI text.

    **The rank indices are joined; the permission ones are not.** Four role names
    against the save's indices 2/3/4 pins a 1-based enum four ways over — see
    `scripts/extract-guild-roles.py` — while eight permission names against
    indices 0-7 agree only on the COUNT. Nothing establishes the order, so
    `permissionOrderKnown` is false and callers must not index into the list.
    """
    global _guild
    if _guild is None:
        try:
            with gzip.open(GUILD_PATH, "rt", encoding="utf-8") as f:
                _guild = json.load(f)
        except (OSError, json.JSONDecodeError) as e:
            logger.warning("Guild role data unavailable (%s)", e)
            _guild = {}
    return _guild


def guild_role_name(index: int) -> str:
    """A rank's display name, or a labelled fallback — never a bare number."""
    entry = (guild_roles().get("roles") or {}).get(str(index))
    return str((entry or {}).get("name") or f"Rank {index}")
